# Generated by Django 5.1.2 on 2024-10-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tool_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
